version: "3.0"
services:
  databus-download:
    image: dbpedia/dbpedia-databus-collection-downloader:latest
    environment:
      COLLECTION_URI: https://databus.dbpedia.org/cringwald/collections/french_chapter
      TARGET_DIR: /root/data
    volumes:
      - /appli/databus-data:/root/data
