version: "3.0"
services:
  databus-download:
    image: dbpedia/dbpedia-databus-collection-downloader:latest
    environment:
      COLLECTION_URI: https://databus.dbpedia.org/dbpedia/collections/latest-core
      TARGET_DIR: /root/data
    volumes:
      - ./download:/root/data
