FROM alpine:3.14
RUN apt-get update
RUN \
  apt-get update && \
  apt-get install bash curl  ca-certificates && \
  apt-get clean

COPY ./light_app /light_app

WORKDIR /light_app

ENTRYPOINT /bin/bash download_light.sh
