version: "3.0"
services:
  databus-download:
    image: databus-download-min:latest
    environment:
      COLLECTION_URI: https://databus.dbpedia.org/jan/collections/lookup
      TARGET_DIR: /root/data
    volumes:
      - ./download:/root/data
