version: "3.0"
services:
  databus-download:
    build :
       context: ./client
       dockerfile: Dockerfile
    environment:
      COLLECTION_URI: https://databus.dbpedia.org/cringwald/collections/french_chapter
      TARGET_DIR: /root/data
    volumes:
      - /appli/databus-data:/root/data
